version: "3"

services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}